#!/usr/bin/with-contenv bash

# create our folders
mkdir -p \
       /config/certs

# copy default config if not present in /config
[[ ! -e /config/shellinabox.conf ]] && \
        cp /etc/default/shellinabox /config/shellinabox.conf


# permissions
chown -R abc:abc \
        /config
